language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t saralkhandelwal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saralkhandelwal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-610300507493"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_key

 

